###
GET http://localhost:3000/api/productos

###
POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "name":"Kas Limon",
    "category": "Bebidas",
    "section": "Refrescos",
    "price": "1",
    "description": "Brick de 1 L de kas sabor limon",
    "quantity":"2" 
}
###
GET http://localhost:3000/api/productos/6231d50b73d67e707c485f49
//esto es pa q devuelva solo un producto
###
DELETE http://localhost:3000/api/productos/6231d59d73d67e707c485f4c

###
PUT http://localhost:3000/api/productos/6231d50b73d67e707c485f49
Content-Type: application/json

{
    "name": "Coca-Cola Zero",
    "description": "Botella de 1 Litro de Coca-Cola Zero"
}
//actualizar cositas